/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    media: Media;
    aiModelsOptions: AiModelsOption;
    'ai-prompts': AiPrompt;
    'ai-presets': AiPreset;
    'ai-composer': AiComposer;
    'ai-composer-ui': AiComposerUi;
    'test-messages': TestMessage;
    'test-products': TestProduct;
    'test-announcements': TestAnnouncement;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    aiModelsOptions: AiModelsOptionsSelect<false> | AiModelsOptionsSelect<true>;
    'ai-prompts': AiPromptsSelect<false> | AiPromptsSelect<true>;
    'ai-presets': AiPresetsSelect<false> | AiPresetsSelect<true>;
    'ai-composer': AiComposerSelect<false> | AiComposerSelect<true>;
    'ai-composer-ui': AiComposerUiSelect<false> | AiComposerUiSelect<true>;
    'test-messages': TestMessagesSelect<false> | TestMessagesSelect<true>;
    'test-products': TestProductsSelect<false> | TestProductsSelect<true>;
    'test-announcements': TestAnnouncementsSelect<false> | TestAnnouncementsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  slug: string;
  content?: AiHtmlBlockType[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AiHtmlBlockType".
 */
export interface AiHtmlBlockType {
  /**
   * Select an AI prompt document whose generated HTML, CSS, JS, and variables should be rendered by this block.
   */
  code: string | AiPrompt;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ai-html-block';
}
/**
 * Generate HTML block code that can be pasted into Payload blocks fields.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-prompts".
 */
export interface AiPrompt {
  id: string;
  title: string;
  /**
   * Optional preset that defines system prompt, provider, and model.
   */
  preset?: (string | null) | AiPreset;
  /**
   * Describe the block you want to generate.
   */
  instructions: string;
  /**
   * Optional images or files to pass to the AI as reference material for this prompt or follow-up.
   */
  referenceFiles?: (string | Media)[] | null;
  /**
   * Optional reference collection queries for preview/rendering data.
   */
  referenceCollections?:
    | {
        /**
         * Collection to query for this reference data source.
         */
        collection: 'test-messages' | 'test-products' | 'test-announcements' | 'users' | 'posts';
        /**
         * Maximum number of documents to load from this collection.
         */
        limit: number;
        /**
         * Marks whether this reference collection is currently used by the prompt.
         */
        isBeingUsed?: boolean | null;
        /**
         * Load now on the server or defer for a future client-side Payload API path.
         */
        dataLoading: 'server' | 'client';
        /**
         * Optional Payload where filter JSON for this collection.
         */
        filtersJSON?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Persisted conversation history used for follow-up AI edits.
   */
  messages?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Persisted summary of the last AI generation run.
   */
  lastRun?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Generated HTML for the ai-html-block.
   */
  html: string;
  /**
   * Optional generated CSS for the ai-html-block.
   */
  css?: string | null;
  /**
   * Optional generated JavaScript for the ai-html-block.
   */
  js?: string | null;
  /**
   * JSON array for the block variables field. Example: [{"key":"heading","value":"Hello"}]
   */
  variablesJSON?: string | null;
  /**
   * Optional JSON payload for the block data field.
   */
  dataJSON?: string | null;
  /**
   * Ready-to-paste Payload blocks item for slug "ai-html-block".
   */
  blockPayloadJSON?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Reusable AI presets that can be linked to from AI prompts. Define the system prompt, provider, and model to use.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-presets".
 */
export interface AiPreset {
  id: string;
  title: string;
  description?: string | null;
  /**
   * This instruction is prepended before the ad-hoc request from the AI composer.
   */
  systemPrompt: string;
  provider: 'google' | 'openai';
  /**
   * Optional explicit model. Leave empty to use the plugin default for the selected provider.
   */
  model?: (string | null) | AiModelsOption;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registry of package-supported AI models. Synced automatically on init and used by AI presets.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aiModelsOptions".
 */
export interface AiModelsOption {
  id: string;
  name: string;
  provider: 'google' | 'openai';
  modelId: string;
  description?: string | null;
  /**
   * If true, this model will still be available for selection in AI presets, but it will be marked as deprecated in the admin UI.
   */
  isDeprecated?: boolean | null;
  /**
   * Marked automatically when a model is no longer present in the package-supported model list.
   */
  isRemoved?: boolean | null;
  /**
   * If true, this model will be used as the default for its provider when no model is explicitly selected in an AI preset.
   */
  isDefault?: boolean | null;
  /**
   * If false, this model will not be available for selection in AI presets, but existing presets using it will continue to work.
   */
  isEnabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * AI Composer sessions — plan and generate UI blocks through conversation.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-composer".
 */
export interface AiComposer {
  id: string;
  title: string;
  /**
   * The initial prompt that starts this composition session.
   */
  firstPrompt: string;
  /**
   * Optional AI preset defining model, provider, and system prompt.
   */
  preset?: (string | null) | AiPreset;
  /**
   * Reference collection queries injected into the AI context.
   */
  referenceCollections?:
    | {
        referenceCollection:
          | 'test-messages'
          | 'test-products'
          | 'test-announcements'
          | 'users'
          | 'posts';
        isBeingUsed?: boolean | null;
        limit?: number | null;
        dataLoading: 'server' | 'client';
        filtersJSON?: string | null;
        id?: string | null;
      }[]
    | null;
  messages?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  plan?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * AI-generated multi-file UI outputs linked to a Composer planning session.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-composer-ui".
 */
export interface AiComposerUi {
  id: string;
  title: string;
  status?: ('draft' | 'generating' | 'complete' | 'error') | null;
  /**
   * The planning session this UI was generated from.
   */
  composerSession?: (string | null) | AiComposer;
  /**
   * The generation plan used to produce this UI.
   */
  plan?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Generated source files. index.html is the entry point.
   */
  files?:
    | {
        /**
         * Relative path e.g. index.html, styles.css, script.js
         */
        path: string;
        language: 'html' | 'css' | 'javascript' | 'json' | 'typescript' | 'tsx';
        content: string;
        /**
         * Mark as the main entry point (index.html)
         */
        isEntryPoint?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * AI generation trace — steps, tool calls, token counts.
   */
  generationLog?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-messages".
 */
export interface TestMessage {
  id: string;
  key: string;
  title: string;
  body: string;
  category: 'general' | 'product' | 'support';
  author: string;
  priority: number;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-products".
 */
export interface TestProduct {
  id: string;
  sku: string;
  name: string;
  summary: string;
  category: 'software' | 'service' | 'template';
  price: number;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-announcements".
 */
export interface TestAnnouncement {
  id: string;
  key: string;
  headline: string;
  summary: string;
  audience: 'all' | 'customers' | 'internal';
  startsAt: string;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'aiModelsOptions';
        value: string | AiModelsOption;
      } | null)
    | ({
        relationTo: 'ai-prompts';
        value: string | AiPrompt;
      } | null)
    | ({
        relationTo: 'ai-presets';
        value: string | AiPreset;
      } | null)
    | ({
        relationTo: 'ai-composer';
        value: string | AiComposer;
      } | null)
    | ({
        relationTo: 'ai-composer-ui';
        value: string | AiComposerUi;
      } | null)
    | ({
        relationTo: 'test-messages';
        value: string | TestMessage;
      } | null)
    | ({
        relationTo: 'test-products';
        value: string | TestProduct;
      } | null)
    | ({
        relationTo: 'test-announcements';
        value: string | TestAnnouncement;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?:
    | T
    | {
        'ai-html-block'?: T | AiHtmlBlockTypeSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AiHtmlBlockType_select".
 */
export interface AiHtmlBlockTypeSelect<T extends boolean = true> {
  code?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aiModelsOptions_select".
 */
export interface AiModelsOptionsSelect<T extends boolean = true> {
  name?: T;
  provider?: T;
  modelId?: T;
  description?: T;
  isDeprecated?: T;
  isRemoved?: T;
  isDefault?: T;
  isEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-prompts_select".
 */
export interface AiPromptsSelect<T extends boolean = true> {
  title?: T;
  preset?: T;
  instructions?: T;
  referenceFiles?: T;
  referenceCollections?:
    | T
    | {
        collection?: T;
        limit?: T;
        isBeingUsed?: T;
        dataLoading?: T;
        filtersJSON?: T;
        id?: T;
      };
  messages?: T;
  lastRun?: T;
  html?: T;
  css?: T;
  js?: T;
  variablesJSON?: T;
  dataJSON?: T;
  blockPayloadJSON?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-presets_select".
 */
export interface AiPresetsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  systemPrompt?: T;
  provider?: T;
  model?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-composer_select".
 */
export interface AiComposerSelect<T extends boolean = true> {
  title?: T;
  firstPrompt?: T;
  preset?: T;
  referenceCollections?:
    | T
    | {
        referenceCollection?: T;
        isBeingUsed?: T;
        limit?: T;
        dataLoading?: T;
        filtersJSON?: T;
        id?: T;
      };
  messages?: T;
  plan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-composer-ui_select".
 */
export interface AiComposerUiSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  composerSession?: T;
  plan?: T;
  files?:
    | T
    | {
        path?: T;
        language?: T;
        content?: T;
        isEntryPoint?: T;
        id?: T;
      };
  generationLog?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-messages_select".
 */
export interface TestMessagesSelect<T extends boolean = true> {
  key?: T;
  title?: T;
  body?: T;
  category?: T;
  author?: T;
  priority?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-products_select".
 */
export interface TestProductsSelect<T extends boolean = true> {
  sku?: T;
  name?: T;
  summary?: T;
  category?: T;
  price?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-announcements_select".
 */
export interface TestAnnouncementsSelect<T extends boolean = true> {
  key?: T;
  headline?: T;
  summary?: T;
  audience?: T;
  startsAt?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
