type Args = {
  children: React.ReactNode;
};

const Layout = ({ children }: Args) => (
  <html lang="en">
    <head>
      <title>AI Generate</title>
      <meta name="description" content="Generated by Payload CMS" />
      <link rel="icon" href="/favicon.ico" />
    </head>

    <body>{children}</body>
  </html>
);

export default Layout;
